baseURL = "http://ahodieb.github.io/"
languageCode = "en-us"
title = "Abdallah Hodieb"
theme = "kiss"

[params.info]
homeTitle = "Abdallah Hodieb | Blog"
related = true
codeCopy = true
taxonomiesCount = true
enableSocial = true

[taxonomies]
tag = "tags"
series = "series"

[params.rss]
includeContent = true
authorName = "Abdallah Hodieb"
authorEmail = "abdallah.hodieb@gmail.com"

[params.social]
linkedin = "abdallahhodieb"
github = "ahodieb"
mastodon = "fosstodon.org/@ahodieb"
twitter = "abdallahhodieb"
email = "abdallah.hodieb@gmail.com"
rss = "index.xml"


[params.social.config]
platforms = ["linkedin", "github", "mastodon", "twitter", "email", "rss"]
