baseURL = "http://ahodieb.github.io/"
languageCode = "en-us"
title = "Abdallah Hodieb"
theme = "kiss"

[params.info]
homeTitle = "Abdallah Hodieb | Blog"
related = true
codeCopy = true
taxonomiesCount = true
enableSocial = true

[taxonomies]
tag = "tags"
series = "series"

[params.rss]
includeContent = true
authorName = "Abdallah Hodieb"
authorEmail = "a.bdallah.hodieb+blog@gmail.com"

[params.social]
linkedin = "abdallahhodieb"
github = "ahodieb"

[params.social.config]
platforms = ["linkedin", "github"]
